# Generated by Django 5.2.13 on 2026-09-13 10:05

import django.core.validators
import django.db.models.deletion
import festival.models
import festival.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='جشنواره همگانی نجات غریق ندای امید', max_length=160)),
                ('registration_starts_at', models.DateTimeField()),
                ('registration_ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'جشنواره',
                'verbose_name_plural': 'جشنواره\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'استخر',
                'verbose_name_plural': 'استخرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('min_age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(12)])),
                ('max_age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('all', 'همه'), ('male', 'آقا'), ('female', 'خانم')], default='all', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='festival.festival')),
            ],
            options={
                'verbose_name': 'ماده مسابقه',
                'verbose_name_plural': 'مواد مسابقه',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('age_at_registration', models.PositiveSmallIntegerField()),
                ('insurance_document', models.FileField(upload_to=festival.models.document_path, validators=[festival.validators.validate_document])),
                ('portrait', models.FileField(upload_to=festival.models.document_path, validators=[festival.validators.validate_document])),
                ('birth_certificate', models.FileField(upload_to=festival.models.document_path, validators=[festival.validators.validate_document])),
                ('payment_receipt', models.FileField(upload_to=festival.models.document_path, validators=[festival.validators.validate_document])),
                ('terms_accepted_at', models.DateTimeField()),
                ('insurance_confirmed_at', models.DateTimeField()),
                ('payment_confirmed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('events', models.ManyToManyField(related_name='registrations', to='festival.competitionevent')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='festival.festival')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='festival.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'constraints': [models.UniqueConstraint(fields=('user', 'festival'), name='one_registration_per_user_per_festival')],
            },
        ),
    ]
