# Generated by Django 5.2.13 on 2026-09-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionevent',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Competition event', 'verbose_name_plural': 'Competition events'},
        ),
        migrations.AlterModelOptions(
            name='festival',
            options={'verbose_name': 'Festival', 'verbose_name_plural': 'Festivals'},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ['name'], 'verbose_name': 'Pool', 'verbose_name_plural': 'Pools'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterField(
            model_name='competitionevent',
            name='gender',
            field=models.CharField(choices=[('all', 'All'), ('male', 'Male'), ('female', 'Female')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='festival',
            name='title',
            field=models.CharField(default='Neda Omid Lifeguard Festival', max_length=160),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
    ]
