# Generated by Django 5.2.13 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0002_alter_competitionevent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festival",
            name="title",
            field=models.CharField(default="جشنواره همگانی نجات غریق (ندای امید)", max_length=160),
        ),
    ]
